
import React from 'react';
import { useStore } from '../context/StoreContext';
import { Shield, CheckCircle, Lock, User as UserIcon, AlertCircle } from 'lucide-react';
export const UserCenter: React.FC = () => {
  const { currentUser, t, verifyKYC, toggle2FA } = useStore();
  if (!currentUser) return <div className="p-10 text-center text-[#848e9c]">Please Log In</div>;
  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 py-12">
      <h1 className="text-2xl font-bold text-white mb-8">{t('user_center')}</h1>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
        <div className="md:col-span-1 space-y-8"><div className="bg-[#1e2329] border border-[#2b3139] rounded-2xl p-6 text-center"><div className="w-24 h-24 bg-[#2b3139] rounded-full mx-auto mb-4 flex items-center justify-center text-[#848e9c]"><UserIcon size={48} /></div><div className="text-white font-bold text-lg mb-1">{currentUser.email}</div><div className="text-[#848e9c] text-sm mb-4">UID: {currentUser.id}</div><div className="inline-block px-3 py-1 bg-[#f0b90b]/10 text-[#f0b90b] rounded font-bold text-xs uppercase border border-[#f0b90b]/20">{currentUser.kycLevel >= 2 ? 'Verified' : 'Unverified'}</div></div><div className="bg-[#1e2329] border border-[#2b3139] rounded-2xl p-6"><h3 className="text-white font-bold mb-4 flex items-center gap-2"> {t('login_history')}</h3><div className="space-y-4">{[1, 2, 3].map(i => (<div key={i} className="flex justify-between text-sm"><span className="text-[#848e9c]">2024-05-2{i} 14:30:00</span><span className="text-white">192.168.1.{i}</span></div>))}</div></div></div>
        <div className="md:col-span-2 space-y-6"><div className="bg-[#1e2329] border border-[#2b3139] rounded-2xl p-8"><h2 className="text-xl font-bold text-white mb-6 flex items-center gap-2"><Shield className="text-[#0ea5e9]" /> {t('security')}</h2><div className="space-y-6"><div className="flex items-center justify-between pb-6 border-b border-[#2b3139]"><div className="flex items-center gap-4"><Lock size={24} className="text-[#848e9c]" /><div><div className="text-white font-bold">Login Password</div><div className="text-[#848e9c] text-sm">Used for login and security checks</div></div></div><button className="px-4 py-2 border border-[#2b3139] rounded text-white hover:border-[#0ea5e9] hover:text-[#0ea5e9] transition-colors">Change</button></div><div className="flex items-center justify-between pb-6 border-b border-[#2b3139]"><div className="flex items-center gap-4"><div><div className="text-white font-bold">Phone Verification (2FA)</div><div className="text-[#848e9c] text-sm">Protect your account and withdrawals</div></div></div><button onClick={toggle2FA} className="px-4 py-2 bg-[#0ea5e9] text-white rounded font-bold hover:bg-[#0284c7]">Enable</button></div><div className="flex items-center justify-between"><div className="flex items-center gap-4"><AlertCircle size={24} className={currentUser.kycLevel >= 2 ? "text-[#0ecb81]" : "text-[#848e9c]"} /><div><div className="text-white font-bold">Identity Verification</div><div className="text-[#848e9c] text-sm">Current: {currentUser.kycLevel >= 2 ? 'Verified' : 'Unverified'}</div></div></div>{currentUser.kycLevel < 2 ? (<button onClick={verifyKYC} className="flex items-center gap-2 px-4 py-2 border border-[#f0b90b] text-[#f0b90b] rounded font-bold hover:bg-[#f0b90b]/10">Verify Now</button>) : (<button disabled className="flex items-center gap-2 px-4 py-2 bg-[#0ecb81]/10 text-[#0ecb81] rounded font-bold border border-[#0ecb81]/20"><CheckCircle size={16} /> Verified</button>)}</div></div></div><div className="bg-[#1e2329] border border-[#2b3139] rounded-2xl p-8"><h2 className="text-xl font-bold text-white mb-6 flex items-center gap-2"><CheckCircle className="text-[#0ecb81]" /> Account Limits</h2><div className="grid grid-cols-2 gap-4"><div className="bg-[#0b0e11] p-4 rounded-xl border border-[#2b3139]"><div className="text-[#848e9c] text-xs uppercase mb-1">Daily Withdrawal</div><div className="text-white font-mono text-xl">{currentUser.kycLevel >= 2 ? '100.00 BTC' : '2.00 BTC'}</div></div><div className="bg-[#0b0e11] p-4 rounded-xl border border-[#2b3139]"><div className="text-xs text-[#848e9c] uppercase mb-1">P2P Trade</div><div className="text-white font-mono text-xl">Unlimited</div></div></div></div></div>
      </div>
    </div>
  );
};
